### ISSUE TITLE
.run() doesn't invokes for lazyloaded modules in 1.0.3 after fix for .config() invoking. 

### ISSUE THREAD

**Issue by captify-ddavydov** [ocombe/ocLazyLoad#218] opened 2015-07-27 14:17 UTC
// I'm lazy-loaded module
angular.module('myModule', ['ngTable'])
.config(function() {
        alert('I'm invoked');
    })
    .run(function() {
        alert('Can't invoke( ');
    })

**Comment by ocombe** [comment] 2015-07-27 14:18
probable duplicate of https://github.com/ocombe/ocLazyLoad/issues/217

**Closed** 2015-07-30 20:58 UTC
Labels: bug

**Comment by ocombe** [comment] 2015-07-30 21:07
Fixed in 1.0.4, thanks for the report !

**Comment by captify-ddavydov** [comment] 2015-07-31 12:10
Now it works! Thank a lot!
