### ISSUE TITLE
Dependency of $templateCache not resolved correctly in .run of a dependency

### ISSUE THREAD

**Issue by iJungleboy** [ocombe/ocLazyLoad#258] opened 2015-10-25 10:38 UTC
Here's the scenario: i'm using Angular Formly and based on the form configuration sometimes it has to download additional custom field-UIs. each field UI is a separate module which uses this kind of setup...

    angular.module("ToSicEavCustomGps", []) 
        .config(function(formlyConfigProvider, defaultFieldWrappers) {

            formlyConfigProvider.setType({
                name: "custom-gps",
                templateUrl: "fields/custom-gps/custom-gps.html",
                wrapper: defaultFieldWrappers,
                controller: "FieldTemplate-CustomGpsController"
            });
        })

the templates are in HTML files which get placed in the $templateCache by a grunt process angular-templates - resulting in this code being loaded in the same file as the previous angular-module:

```
angular.module('tempCustomGpsTmplates',[]).run(['$templateCache', function($templateCache) {
  'use strict';

  $templateCache.put('fields/custom-gps/custom-gps.html',
    "<div><div class=\"alert alert-danger\">GPS-Picker 2 - not implemented yet <input class=\"form-control input-lg\" ng-pattern=vm.regexPattern ng-model=value.Value></div><div ng-if=debug.on><h4>debug info</h4><div>lat field name: '{{ latField}}' long-field name: '{{longField}}'</div></div></div>"
  );

}]);
```

this throws an error atht $templateCacheProvider is missing.

alternately if I place the code in a service (manually, because the grunt-job won't do this) it works: 

```
    // tests w/template cache
    .service("addtemplatestocache", //)
        function ($templateCache) {
        $templateCache.put('fields/custom-gps/custom-gps.html',
          "<div><div class=\"alert alert-danger\">GPS-Picker 2 - not implemented yet <input class=\"form-control input-lg\" ng-pattern=vm.regexPattern ng-model=value.Value></div><div ng-if=debug.on><h4>debug info</h4><div>lat field name: '{{ latField}}' long-field name: '{{longField}}'</div></div></div>"
        );

    })
```

so apparently $templateCache is resolved properly in a service call, but not in the run. Is this a bug or am I missing something?

**Comment by ocombe** [comment] 2015-10-25 10:44
Hmm might be a bug, could you make me a plunkr (I don't need all the code, only a lazy loaded module with a run and $templateCache) so that I can check the things out ?

**Comment by iJungleboy** [comment] 2015-10-26 05:54
I've tried to set it all up here http://plnkr.co/edit/HeTXcbn0Fd8CK9lbJ7JO 
but i have never plunkrd before, so I don't really know what to do. where would I see/find the errors?

**Comment by ocombe** [comment] 2015-10-26 10:57
You can look in the console when you click on the run button.
It works in your plunkr (run is executed with no error), so the problem is probably somewhere else.

**Comment by matoilic** [comment] 2015-11-25 10:07
I have the same issue when I try to lazily load UI Bootstrap https://www.npmjs.com/package/angular-ui-bootstrap. Here is the stack trace:

Error: [$injector:unpr] Unknown provider: $templateCacheProvider <- $templateCache
http://errors.angularjs.org/1.4.8/$injector/unpr?p0=%24templateCacheProvider%20%3C-%20%24templateCache
    at http://localhost:8088/jspm_packages/github/angular/bower-angular@1.4.8/angular.js:71:12
    at http://localhost:8088/jspm_packages/github/angular/bower-angular@1.4.8/angular.js:4337:19
    at Object.getService [as get] (http://localhost:8088/jspm_packages/github/angular/bower-angular@1.4.8/angular.js:4485:39)
    at http://localhost:8088/jspm_packages/github/angular/bower-angular@1.4.8/angular.js:4342:45
    at getService (http://localhost:8088/jspm_packages/github/angular/bower-angular@1.4.8/angular.js:4485:39)
    at Object.invoke (http://localhost:8088/jspm_packages/github/angular/bower-angular@1.4.8/angular.js:4517:13)
    at http://localhost:8088/jspm_packages/github/ocombe/oclazyload@1.0.9/dist/ocLazyLoad.js:214:38
    at Object.forEach (http://localhost:8088/jspm_packages/github/angular/bower-angular@1.4.8/angular.js:343:20)
    at _register (http://localhost:8088/jspm_packages/github/ocombe/oclazyload@1.0.9/dist/ocLazyLoad.js:213:25)
    at _register (http://localhost:8088/jspm_packages/github/ocombe/oclazyload@1.0.9/dist/ocLazyLoad.js:193:25)

**Comment by matoilic** [comment] 2015-11-25 22:10
After some deep digging, I've found out that in my case the issue is caused by UI Router. I've a ui-view directive on the root element. As soon as the first state gets rendered UI Router then replaces the root element with a comment node. This causes the loss of all data set on that element.

Since ocLazyLoad uses the root element to get $injector, it gets back a null value and falls back to creating a new injector instance. So, in the end it's a bug in UI Router and not ocLazyLoad.

**Comment by ocombe** [comment] 2015-11-25 22:16
Hmm this reminds me of something, I think that I came across that problem a long time ago, I'm not sure what the solution was though

**Comment by timelf123** [comment] 2015-12-04 22:25
@matoilic did you find/file an issue at [ui-router](https://github.com/angular-ui/ui-router/issues)?

**Comment by matoilic** [comment] 2015-12-05 10:07
I did. But it seems like they don't really care about fixing it https://github.com/angular-ui/ui-router/issues/2398

**Comment by iJungleboy** [comment] 2015-12-07 07:08
This sucks a bit. I'm not sure if such data can actually be moved to a "comment" in the dom. So is it possible to do what he writes "set ui-view as a child"? Is that something that's in the control of oclazyload?

**Comment by ocombe** [comment] 2015-12-07 08:38
Not really no, it would be a race condition between ui router and ocLazyLoad, so nothing really fixable by code...
You could fill in a PR for ui-router with a fix for this ?

**Comment by matoilic** [comment] 2015-12-07 08:49
The easiest way to overcome the issue is to switch from

```html
<div id="app" ui-view="appView"></div>
```

to 

```html
<div id="app">
    <ui-view name="appView"></ui-view>
</div>
```

I'll try to submit a PR if I find some time in the next few weeks. I'm also curious if the Angular team will finally release their new router with 1.5, which could replace UI Router.

**Comment by ocombe** [comment] 2015-12-07 08:50
Yes, closing this issue as it is a problem with ui router :)

**Closed by ocombe** 2015-12-07 08:50 UTC
