### ISSUE TITLE
unable to init ocLazyLoad using Jasmine test runner

### ISSUE THREAD

**Issue by craigg75** [ocombe/ocLazyLoad#129] opened 2015-02-10 02:21 UTC
I have a lot of Jasmine tests that I've been running for several months successfully. I recently started using the wonderful ocLazyLoad module. But now I'm getting this error on all tests --

_No module found during bootstrap, unable to init ocLazyLoad_

I'm not really sure how to try to work around this bug. I noticed in another issue #123 that a user noticed that if you load it before the mocks.js file it works. I tried that and have used the latest ocLazyLoad.js from the src folder. Neither one of these ideas worked :(

**Comment by ocombe** [comment] 2015-02-10 08:34
Hi, have you tested with the file in the src folder from the current master ? I've made changes recently but haven't released a new version yet.

**Comment by craigg75** [comment] 2015-02-10 14:22
Yes I tried that last night since I noticed you were having others try the version from the src folder to get through this issue. As a temporary fix I may just create a separate app.js and index.html file that doesn't include the ocLazyLoad module. I'm sure you will fix this at some point and I don't want you to feel rushed. I'd try my hand at helping you with this but I consider myself to still be a newbie with angular and I still haven't groked what's going on underneath :)

**Comment by ocombe** [comment] 2015-02-10 15:07
Okay :)
Yes this should be fixed soon I hope.

**Comment by kloy** [comment] 2015-02-14 03:47
I am creating a dummy module that depends on ocLacyLoad and bootstraps before the tests are executed. This solves the issue albeit very hackish.

**Comment by roymilder** [comment] 2015-02-21 10:19
Just want to confirm that I had the same issue (No module found during bootstrap, unable to init ocLazyLoad) and that the current master in the src folder did fix the issue.

thanks

**Comment by carlos-algms** [comment] 2015-02-26 17:13
Hi, created a jsfiddle that reproduces the error.

https://jsfiddle.net/carlosalgms/ga3etdvo/2/

Apparently the error only raises if a decribe() have 2 or more it() insede.
If you have only 1 it(), the test runs successfully.

**Comment by carlos-algms** [comment] 2015-02-26 19:25
How we can insert content into phantomJS before he init the tests?
Because if I insert a div with ng-app, the tests runs smoothly.

Ex:
http://jsfiddle.net/carlosalgms/ga3etdvo/

**Comment by ocombe** [comment] 2015-02-26 19:39
Well phantomJS is an headless browser but it's a browser nonetheless, so it should work the same as for chrome or firefox.
You need to instantiate your app one way or the other: with an ng-app directive, or with angular.bootstrap.
If you don't, it's not a regular Angular App and ocLazyLoad won't work for now. The new version I'm working on should be easier to test.

I forked your jsfiddle and added the angular.bootstrap to make it work without any DOM: http://jsfiddle.net/562uq3zx/

**Closed** 2015-02-26 22:50 UTC
Labels: bug

**Comment by ocombe** [comment] 2015-02-26 23:17
It should be fixed in 0.6.0!

**Comment by gustavolira** [comment] 2015-02-27 01:46
Hi @ocombe , sorry to be inconvinience... I just updated to 0.6.0 and I'm receiving the same error.
I'm receiving:
Running "karma:unit" (karma) task
INFO [karma]: Karma v0.12.31 server started at http://localhost:8083/
INFO [launcher]: Starting browser PhantomJS
INFO [PhantomJS 1.9.8 (Linux)]: Connected on socket ayS0NvUwA4VOlxyEtXKW with id 45489088
WARN [web-server]: 404: /undefined
PhantomJS 1.9.8 (Linux): Executed 0 of 1 ERROR (0.001 secs / 0 secs)
Warning: Task "karma:unit" failed. Use --force to continue.

**Comment by ocombe** [comment] 2015-02-27 07:27
@gustavolira could you make me a small zip with a minimal test case so that I can find out what the problem is please ? Send it to olivier.combe@gmail.com

**Comment by craigg75** [comment] 2015-02-27 15:30
Thanks for the fix, works great in Jasmine now!
